---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: namespace-node-affinity

resources:
- deployment.yaml
- role.yaml
- rolebinding.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- sa.yaml
- service.yaml
