---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-node-affinity
  namespace: default
subjects:
- kind: ServiceAccount
  name: namespace-node-affinity
  namespace: default
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-node-affinity
  apiGroup: rbac.authorization.k8s.io
