apiVersion: v1
kind: Service
metadata:
  name: namespace-node-affinity
  labels:
    app: namespace-node-affinity
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: namespace-node-affinity
