apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployments.fullname" . }}
  labels:
    {{- include "deployments.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
