kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-node-affinity
subjects:
- kind: ServiceAccount
  name: namespace-node-affinity
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-node-affinity
  apiGroup: rbac.authorization.k8s.io
