name: Build and push docker images

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
      - 'v*.*'

  workflow_run:
    workflows:
      - 'Test'
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
      - 'v*.*'
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            idgenchev/namespace-node-affinity
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Docker meta for the init container
        id: initmeta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            idgenchev/namespace-node-affinity-init-container
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Webhook image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push init container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/DockerfileInitContainer
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: ${{ steps.initmeta.outputs.tags }}
          labels: ${{ steps.initmeta.outputs.labels }}
