name: Test

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
      - 'v*.*'
  pull_request:
    branches:
      - 'main'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: go get -u golang.org/x/lint/golint

      - name: Lint
        run: golint -set_exit_status ./...

      - name: Check gofmt
        run: ./scripts/gofmt-check.sh

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
